### ISSUE TITLE
ModuleNotFoundError: No module named 'minifier'

### ISSUE THREAD

**Issue by klint-k** [berniey/html5print#13]
from html5print import HTMLBeautifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/XXXXX/.local/lib/python3.9/site-packages/html5print/__init__.py", line 20, in <module>
    from .jsprint import JSBeautifier
  File "/home/XXXXX/.local/lib/python3.9/site-packages/html5print/jsprint.py", line 22, in <module>
    import slimit
  File "/home/XXXXX/.local/lib/python3.9/site-packages/slimit/__init__.py", line 27, in <module>
    from minifier import minify
ModuleNotFoundError: No module named 'minifier'

**Comment by MattReimer** [comment]
Just FYI I got my developers unblocked by installing the latest git ref of slimit

```bash
pip3 install pip install git+https://github.com/rspivak/slimit.git@3533eba9ad5b39f3a015ae6269670022ab310847
```

I'm not sure what the long term solution is though. Seems like both `html5print` and `slimit` are no longer being actively developed.
